### ISSUE TITLE
Status: error running

### ISSUE THREAD

**Issue by Deafideaf** [jgresham/nice-node#66] opened 2022-09-07 16:44 UTC
Problem description
-

After update to new version, Geth stops with error running.

"Geth Logs

Newest logs at the top
'pm2' is not recognized as an internal or external command,
operable program or batch file."

Any help would be appreciated.

For NiceNode developers
-
{
  "platform": "win32",
  "platformRelease": "10.0.17763",
  "arch": "x64",
  "totalMemory": 137359765504,
  "niceNodeVersion": "1.5.1-alpha"
}

**Comment by jgresham** [comment] 2022-10-31 16:05
Duplicate of #40

**Closed** 2022-10-31 16:05 UTC
